# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed
# correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place
# is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses
# the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell
# the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:

import random

class bull_cow_game:
    def __init__(self):
        self.comp_no = str(random.randint(1000,9999))
        self.win = 0
        self.guess_count = 0
        print(f"Comp is: {self.comp_no}")

    def guess(self,guess_str):
        i = 0
        for x in range(0,len(guess_str)):
            if guess_str[x] == self.comp_no[x]:
                i += 1
        self.has_won(i)
        self.guess_count += 1
        return i

    def has_won(self,score):
        if score == 4:
            self.win = 1

if input("Do you want to play (y/n): ") == "y":

    newGame = bull_cow_game()

    while newGame.win == 0:
        player_guess = str(input("Guess the 4 digit number:"))
        print(f"You got {newGame.guess(player_guess)} correct - {newGame.guess_count} guesses so far...")

    print("You win")

else:
    print("Goodbye")